apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: my_docker_image
        ports:
        - containerPort: 443
          name: https
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: myvolume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: myclaim
